

function printTransferOrder(request, response) {
    var recordID = request.getParameter('recID');
    nlapiLogExecution('DEBUG', 'ID', recordID)

    var billRec = nlapiLoadRecord("vendorbill", recordID);


    var sub_id = billRec.getFieldValue("subsidiary");
    var subRec = nlapiLoadRecord("subsidiary", sub_id);

    var vendorId = billRec.getFieldValue("entity");

    var vendorRec =  nlapiLoadRecord("vendor", vendorId);

    var bankCount = vendorRec.getLineItemCount("recmachcustrecord_bank_vendor_ref");
   nlapiLogExecution("debug","bankCount",bankCount);



    var renderer = nlapiCreateTemplateRenderer();
    var template = "";

    template += "<?xml version=\"1.0\"?><!DOCTYPE pdf PUBLIC \"-//big.faceless.org//report\" \"report-1.1.dtd\"> "
    template += "<pdf> "
    template += "<head> "
    template += "	<link name=\"NotoSans\" type=\"font\" subtype=\"truetype\" src=\"${nsfont.NotoSans_Regular}\" src-bold=\"${nsfont.NotoSans_Bold}\" src-italic=\"${nsfont.NotoSans_Italic}\" src-bolditalic=\"${nsfont.NotoSans_BoldItalic}\" bytes=\"2\" /> "
    template += "	<#"
    template += "if .locale == \"zh_CN\"> "
    template += "		<link name=\"NotoSansCJKsc\" type=\"font\" subtype=\"opentype\" src=\"${nsfont.NotoSansCJKsc_Regular}\" src-bold=\"${nsfont.NotoSansCJKsc_Bold}\" bytes=\"2\" /> "
    template += "	<#elseif .locale == \"zh_TW\"> "
    template += "		<link name=\"NotoSansCJKtc\" type=\"font\" subtype=\"opentype\" src=\"${nsfont.NotoSansCJKtc_Regular}\" src-bold=\"${nsfont.NotoSansCJKtc_Bold}\" bytes=\"2\" /> "
    template += "	<#elseif .locale == \"ja_JP\"> "
    template += "		<link name=\"NotoSansCJKjp\" type=\"font\" subtype=\"opentype\" src=\"${nsfont.NotoSansCJKjp_Regular}\" src-bold=\"${nsfont.NotoSansCJKjp_Bold}\" bytes=\"2\" /> "
    template += "	<#elseif .locale == \"ko_KR\"> "
    template += "		<link name=\"NotoSansCJKkr\" type=\"font\" subtype=\"opentype\" src=\"${nsfont.NotoSansCJKkr_Regular}\" src-bold=\"${nsfont.NotoSansCJKkr_Bold}\" bytes=\"2\" /> "
    template += "	<#elseif .locale == \"th_TH\"> "
    template += "		<link name=\"NotoSansThai\" type=\"font\" subtype=\"opentype\" src=\"${nsfont.NotoSansThai_Regular}\" src-bold=\"${nsfont.NotoSansThai_Bold}\" bytes=\"2\" /> "
    template += "	</#if> "
    template += "    <macrolist> "
    template += "        <macro id=\"nlheader\"> "
    template += " "
    template += "        <table class=\"header\" style=\"width: 100%;height:90px;\"> "
    template += "            <tr > "
    template += "                <td style=\"width:100%;\"> "
    template += "                    <img src=\"${companyInformation.logoUrl}\" style=\" align:right;height:120px;width:150px;\"/> "
    // template += "                <#if subsidiary.logo@url?has_content> "
    // template += "                     <img src=\"${subsidiary.logo@url}\">"//style=\"align:right;height:100px;width:150px;top:-10px;padding-top:-10px;padding-bottom:25px;\"/
    // template += "               	 "
    // template += "                <#else> "
    // template += "                    <img src=\"${companyInformation.logoUrl}\" style=\"\"/> "
    // template += "                </#if> "
    template += "                 "
    template += "                    "
    template += "                </td> "
    template += "	        </tr> "
    template += "        </table> "
    template += "        </macro> "
    template += "        <macro id=\"nlfooter\"> "
    template += "            <table class=\"footer\"><tr> "
    template += "	<td align=\"right\"><pagenumber/> of <totalpages/></td> "
    template += "	</tr></table> "
    template += "        </macro> "
    template += "    </macrolist> "
    template += "    <style type=\"text/css\">span, table "
    template += "{                        <#if .locale==\"zh_CN\">font-family: stsong, sans-serif; "
    template += "                            <#elseif .locale==\"zh_TW\">font-family: msung, sans-serif; "
    template += "                                <#elseif .locale==\"ja_JP\">font-family: heiseimin, sans-serif; "
    template += "                                    <#elseif .locale==\"ko_KR\">font-family: hygothic, sans-serif; "
    template += "                                        <#elseif .locale==\"ru_RU\">font-family: verdana; "
    template += "                                            <#else>font-family: sans-serif; "
    template += "                                            </#if>font-size: 9pt; "
    template += "		table-layout: fixed; "
    template += "		} "
    template += "		th "
    template += "{		font-weight: bold; "
    template += "		font-size: 8.5pt; "
    template += "		padding-top: 2px; "
    template += "		vertical-align: middle; "
    template += "		/*padding: 3px 6px 10px;*/ "
    template += "		/*background-color: #e3e3e3; "
    template += "		color: #333333;*/ "
    template += "		} "
    template += "		b "
    template += "{		font-weight: bold; "
    template += "		color: #333333; "
    template += "		} "
    template += "		table.header td "
    template += "{		padding: 0; "
    template += "		font-size: 10pt; "
    template += "		} "
    template += "		table.footer td "
    template += "{		padding: 0; "
    template += "		font-size: 8pt; "
    template += "		} "
    template += "		#itemtable th p "
    template += "{		vertical-align: text-top !important; "
    template += "		text-align: center !important; "
    template += "		} "
    template += "		#itemtable "
    template += "{		font-size: 8.5pt !important; "
    template += "		border: 0.5px solid #000000 "
    template += "		} "
    template += "		table.total "
    template += "{		page-break-inside: avoid; "
    template += "		} "
    template += "		tr.totalrow "
    template += "{		background-color: #e3e3e3; "
    template += "		line-height: 200%; "
    template += "		} "
    template += "		td.totalboxtop "
    template += "{		font-size: 12pt; "
    template += "		background-color: #e3e3e3; "
    template += "		} "
    template += "		span.title "
    template += "{		font-size: 28pt; "
    template += "		} "
    template += "		.smallTitle "
    template += "{		font-size: 9pt; "
    template += "		} "
    template += "		span.number "
    template += "{		font-size: 16pt; "
    template += "		text-align:center; "
    template += "		} "
    template += "		span.itemname "
    template += "{		font-weight: bold; "
    template += "		line-height: 150%; "
    template += "		} "
    template += "		hr "
    template += "{		width: 100%; "
    template += "		color: #d3d3d3; "
    template += "		background-color: #d3d3d3; "
    template += "		height: 1px; "
    template += "		} "
    template += "		table.smalltext tr td "
    template += "{		font-size: 8pt; "
    template += "		} "
    template += "		/*table.itemtable th{ "
    template += "border-bottom: 10px #ffc966; "
    template += "border-color: yellow; "
    template += "}*/ "
    template += "		p.alignR "
    template += "{		text-align: right !important; "
    template += "		} "
    template += "		p.alignL "
    template += "{		text-align: left !important; "
    template += "		} "
    template += "		p.alignC "
    template += "{		text-align: center !important; "
    template += "		} "
    template += "		.td_right_line "
    template += "{		/*border-right: 0.5px solid #f4f4f4;*/ "
    template += "		border-right :0.5px solid #000000; "
    template += "		} "
    template += "		.td_bottom_line "
    template += "{		border-bottom: 0.5px solid #000000; "
    template += "		} "
    template += "		.td_top_line "
    template += "{		/*border-top :0.5px solid #f4f4f4;*/ "
    template += "		border-top :0.5px solid #000000; "
    template += "		} "
    template += "		.title "
    template += "{		font-weight: bold; "
    template += "		align:center!important; "
    template += "		font-size:16pt; "
    template += "		} "
    template += "		.footer-img "
    template += "{		/*width: 100%; "
    template += "		height: 20%;*/ "
    template += "		top: 0px; "
    template += "		right: 0px; "
    template += "		left: 0px; "
    template += "		bottom: 0px; "
    template += "		} "
    template += "		.footer "
    template += "{		margin-left:-45px; margin-right:-60px; margin-bottom:-115px; "
    template += "		} "
    template += "		.td_left_line "
    template += "{		/*border-right: 0.5px solid #f4f4f4;*/ "
    template += "		border-left :0.5px solid #000000; "
    template += "		} "
    template += "		.maintbl "
    template += "{		border:0.5px solid #000000; "
    template += "		} "
    template += "		.footertbl "
    template += "{		border:0.5px solid #000000; "
    template += "		border-top: 0px !important; "
    template += "		} "
    template += "		.footertbl2 "
    template += "{		 "
    template += "		/*border:0.5px solid #000000;*/ "
    template += "		border-left: 0.5px solid #000000; "
    template += "		border-right: 0.5px solid #000000; "
    template += "		border-top: 0.25px !important; "
    template += "		} "
    template += "		.pad_left "
    template += "{		padding-left: 5px!important; "
    template += "		} "
    template += "		th,td "
    template += "{		padding:4px; "
    template += "		} "
    template += "		                                                                                                                                                                                                                            <!--  .td_top_line td "
    template += "{		padding-left: 5px!important; "
    template += "		} --> "
    template += "		td img "
    template += "{		max-width:100%; "
    template += "		 "
    template += "		} "
    template += "    </style> "
    template += "</head> "
    template += "<body header=\"nlheader\" header-height=\"10%\" footer=\"nlfooter\" footer-height=\"10pt\" padding=\"0.5in 0.5in 0.5in 0.5in\" size=\"Letter\"> "
    template += "     "
    template += " "
    template += " "
    template += " "
    template += "	 "
    template += "<table width=\"100%\">'; "
    template += "        <tr> "
    template += "            <td align=\"center\" class=\"title\"> "
    template += "                <b><u>Vendor Bill</u></b> "
    template += "            </td> "
    template += "        </tr> "
    template += "    </table> "
    template += "    <table width=\"100%\" border=\"0.5px solid #000000\"> "
    template += "                                         "
    template += "    <tr > "
    template += "        <td width=\"50%\" border-right=\"0.5px solid #000000\"> "
    template += "            <table align=\"right\" width=\"100%\"> "
    template += "                <tr> "
    template += "                    <td align=\"left\" width=\"50%\"> "
    template += "                        <p align=\"left\"><b>Bill To</b></p> "
    template += "                    </td> "
    template += "                    <td width=\"2%\"> "
    template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
    template += "                    </td> "
    template += "                                                             "
    template += "<#if record.entity.isperson?string ==\"Yes\"> "
    template += "                    <td align=\"left\" width=\"48%\"> "
    template += "                        <p align=\"left\"><b>${record.entity.firstname}&nbsp;${record.entity.lastname}</b></p> "
    template += "                    </td> "
    template += "<#else> "
    template += "                    <td align=\"left\" width=\"48%\"> "
    template += "                        <p align=\"left\"><b>${record.entity.companyname}</b></p> "
    template += "                    </td> "
    template += "</#if> "
    template += "                </tr> "
    template += "<#if record.entity.address?has_content> "
    template += "                <tr> "
    template += "                    <td align=\"left\" width=\"50%\"> "
    template += "                        <p align=\"left\"><b>Address</b></p> "
    template += "                    </td> "
    template += "                    <td width=\"2%\"> "
    template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
    template += "                    </td> "
    template += "                    <td align=\"left\" width=\"48%\">${record.entity.address}</td> "
    template += "                </tr> "
    template += "</#if> "
    template += " "
    template += "<#if record.entity.email?has_content> "
    template += "                <tr> "
    template += "                    <td align=\"left\" width=\"50%\"> "
    template += "                        <p align=\"left\"><b>Email</b></p> "
    template += "                    </td> "
    template += "                    <td width=\"2%\"> "
    template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
    template += "                    </td> "
    template += "                    <td align=\"left\" width=\"48%\"> "
    template += "                        <p align=\"left\" style=\"text-decoration:none;\">${record.entity.email}</p> "
    template += "                    </td> "
    template += "                </tr> "
    template += "</#if> "
    template += "<#if record.entity.vatregnumber?has_content> "
    template += "                <tr> "
    template += "                    <td align=\"left\" width=\"50%\"> "
    template += "                        <p align=\"left\"><b>Supplier Tax Registration Number</b></p> "
    template += "                    </td> "
    template += "                    <td width=\"2%\"> "
    template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
    template += "                    </td> "
    template += "                    <td align=\"left\" width=\"48%\"> "
    template += "                        <p align=\"left\" style=\"text-decoration:none;\">${record.entity.vatregnumber}</p> "
    template += "                    </td> "
    template += "                </tr> "
    template += "</#if> "
    template += "<#if record.entity.contact?has_content> "
    template += "                <tr> "
    template += "                    <td align=\"left\" width=\"50%\"> "
    template += "                        <p align=\"left\"><b>Attention</b></p> "
    template += "                    </td> "
    template += "                    <td width=\"2%\"> "
    template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
    template += "                    </td> "
    template += "                    <td align=\"left\" width=\"48%\"> "
    template += "                        <p align=\"left\" style=\"text-decoration:none;\">${record.entity.contact}</p> "
    template += "                    </td> "
    template += "                </tr> "
    template += "</#if>   "
    template += "<#if record.entity.phone?has_content> "
    template += "                <tr> "
    template += "                    <td align=\"left\" width=\"50%\"> "
    template += "                        <p align=\"left\"><b>Tel No</b></p> "
    template += "                    </td> "
    template += "                    <td width=\"2%\"> "
    template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
    template += "                    </td> "
    template += "                    <td align=\"left\" width=\"48%\">${record.entity.phone}</td> "
    template += "                </tr> "
    template += "</#if> "
    //
    for(var i=1;i<=bankCount;i++)
    {
        var bankName =vendorRec.getLineItemValue(
            'recmachcustrecord_bank_vendor_ref',
            'custrecord_bank_name',i
        )
        var acctNumber = vendorRec.getLineItemValue(
            "recmachcustrecord_bank_vendor_ref",
            "custrecord_account_number",
             i
        )
        var currency = vendorRec.getLineItemValue(
             "recmachcustrecord_bank_vendor_ref",
           "custrecord_bank_currency",
           i
        )
        var subsidiary = vendorRec.getLineItemValue(
            "recmachcustrecord_bank_vendor_ref",
             "custrecord_bank_subsidiary",
             i
        )
        var swiftCode = vendorRec.getLineItemValue(
           "recmachcustrecord_bank_vendor_ref",
            "custrecord_bank_swift_code",
             i
        )
        var country = vendorRec.getLineItemValue(
             "recmachcustrecord_bank_vendor_ref",
           "custrecord_bank_country",
             i
        )
        var iBan = vendorRec.getLineItemValue(
             "recmachcustrecord_bank_vendor_ref",
            "custrecord_bank_iban",
            i
        )
        var Defaultcheck = vendorRec.getLineItemValue(
            "recmachcustrecord_bank_vendor_ref",
            "custrecord_default_checkbox",
            i
        )
        if(Defaultcheck=="T")
        {
            if(bankName!==null)
            {
                // template += "<#if bankName?has_content> "
                template += "                <tr> "
                template += "                    <td align=\"left\" width=\"50%\"> "
                template += "                        <p align=\"left\"><b>Bank Name</b></p> "
                template += "                    </td> "
                template += "                    <td width=\"2%\"> "
                template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
                template += "                    </td> "
                template += "                    <td align=\"left\" width=\"48%\">"+bankName+"</td> "
                template += "                </tr> "
                // template += "</#if> "
            }
           if(acctNumber!==null)
           {
            // template += "<#if acctNumber?has_content> "
            template += "                <tr> "
            template += "                    <td align=\"left\" width=\"50%\"> "
            template += "                        <p align=\"left\"><b>Account Number</b></p> "
            template += "                    </td> "
            template += "                    <td width=\"2%\"> "
            template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
            template += "                    </td> "
            template += "                    <td align=\"left\" width=\"48%\">"+acctNumber+"</td> "
            template += "                </tr> "
            // template += "</#if> "
           }
            if(currency!==null)
            {
                // template += "<#if currency?has_content> "
                template += "                <tr> "
                template += "                    <td align=\"left\" width=\"50%\"> "
                template += "                        <p align=\"left\"><b>Currency</b></p> "
                template += "                    </td> "
                template += "                    <td width=\"2%\"> "
                template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
                template += "                    </td> "
                template += "                    <td align=\"left\" width=\"48%\">"+currency+"</td> "
                template += "                </tr> "
                // template += "</#if> "
            }
            if(subsidiary!==null)
            {
                // template += "<#if subsidiary?has_content> "
                template += "                <tr> "
                template += "                    <td align=\"left\" width=\"50%\"> "
                template += "                        <p align=\"left\"><b>Subsidiary</b></p> "
                template += "                    </td> "
                template += "                    <td width=\"2%\"> "
                template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
                template += "                    </td> "
                template += "                    <td align=\"left\" width=\"48%\">"+subsidiary+"</td> "
                template += "                </tr> "
                // template += "</#if> "
            }
          if(swiftCode!==null)
          {
            // template += "<#if swiftCode?has_content> "
            template += "                <tr> "
            template += "                    <td align=\"left\" width=\"50%\"> "
            template += "                        <p align=\"left\"><b>Swift Code</b></p> "
            template += "                    </td> "
            template += "                    <td width=\"2%\"> "
            template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
            template += "                    </td> "
            template += "                    <td align=\"left\" width=\"48%\">"+swiftCode+"</td> "
            template += "                </tr> "
            // template += "</#if> "
          }
        }
   
}
    template += "            </table> "
    template += "             "
    template += "        </td> "
    template += " "
    template += "        <td width=\"50%\"> "
    template += "            <table width=\"100%\"> "
    template += "<#if record.tranid?has_content> "
    template += "                <tr> "
    template += "                    <td align=\"left\" width=\"50%\"> "
    template += "                        <p align=\"left\"><b>Bill#</b></p> "
    template += "                    </td> "
    template += "                    <td width=\"2%\"> "
    template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
    template += "                    </td> "
    template += "                    <td align=\"left\" width=\"48%\">${record.tranid}</td> "
    template += "                </tr> "
    template += "</#if> "
    template += " <#if record.trandate?has_content> "
    template += "                <tr> "
    template += "                    <td align=\"left\" width=\"50%\"> "
    template += "                        <p align=\"left\"><b>Bill Date</b></p> "
    template += "                    </td> "
    template += "                    <td width=\"2%\"> "
    template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
    template += "                    </td> "
    template += "                    <td align=\"left\" width=\"48%\">${record.trandate?string(\"dd-MMM-YYYY\")}</td> "
    template += "                </tr> "
    template += "</#if> "
    template += "<#if record.currencysymbol?has_content> "
    template += "                <tr> "
    template += "                    <td align=\"left\" width=\"50%\"> "
    template += "                        <p align=\"left\"><b>Currency</b></p> "
    template += "                    </td> "
    template += "                    <td width=\"2%\"> "
    template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
    template += "                    </td> "
    template += "                    <td align=\"left\" width=\"48%\">${record.currencysymbol}</td> "
    template += "                </tr> "
    template += "</#if> "
    template += "<#if record.exchangerate?has_content> "
    template += "                <tr> "
    template += "                    <td align=\"left\" width=\"50%\"> "
    template += "                        <p align=\"left\"><b>Exchange Rate</b></p> "
    template += "                    </td> "
    template += "                    <td width=\"2%\"> "
    template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
    template += "                    </td> "
    template += "                    <td align=\"left\" width=\"48%\">${record.exchangerate?string[\"#,##0.00\"]}</td> "
    template += "                </tr> "
    template += "</#if> "
    template += "<#if subsidiary.federalidnumber?has_content> "
    template += "                <tr> "
    template += "                    <td align=\"left\" width=\"50%\"> "
    template += "                        <p align=\"left\"><b>Tax Registration Number</b></p> "
    template += "                    </td> "
    template += "                    <td width=\"2%\"> "
    template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
    template += "                    </td> "
    template += "                    <td align=\"left\" width=\"48%\">${subsidiary.federalidnumber}</td> "
    template += "                </tr> "
    template += " "
    template += "</#if> "
    template += "<#if record.duedate?has_content> "
    template += "                <tr> "
    template += "                    <td align=\"left\" width=\"50%\"> "
    template += "                        <p align=\"left\"><b>Due Date</b></p> "
    template += "                    </td> "
    template += "                    <td width=\"2%\"> "
    template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
    template += "                    </td> "
    template += "                    <td align=\"left\" width=\"48%\">${record.duedate}</td> "
    template += "                </tr> "
    template += "</#if> "
    template += " "
    template += "<#if record.terms?has_content> "
    template += "                <tr> "
    template += "                    <td align=\"left\" width=\"50%\"> "
    template += "                        <p align=\"left\"><b>Payment Terms</b></p> "
    template += "                    </td> "
    template += "                    <td width=\"2%\"> "
    template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
    template += "                    </td> "
    template += "                    <td align=\"left\" width=\"48%\">${record.terms}</td> "
    template += "                </tr> "
    template += "</#if> "
    template += "<#if record.billaddress?has_content> "
    template += "                <tr> "
    template += "                    <td align=\"left\" width=\"50%\"> "
    template += "                        <p align=\"left\"><b>Delivery Address</b></p> "
    template += "                    </td> "
    template += "                    <td width=\"2%\"> "
    template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
    template += "                    </td> "
    template += "                    <td align=\"left\" width=\"48%\">${subsidiary.mainaddress_text}</td> "
    template += "                </tr> "
    template += "</#if> "
    template += "<!-- <#if record.incoterm?has_content> "
    template += "<tr> "
    template += "    <td align=\"left\" width=\"50%\"> "
    template += "        <p align=\"left\"><b>Incoterm</b></p> "
    template += "    </td> "
    template += "    <td width=\"2%\"> "
    template += "        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
    template += "    </td> "
    template += "    <td align=\"left\" width=\"48%\">${record.incoterm}</td> "
    template += "</tr> "
    template += "</#if> --> "
    template += "<#if record.memo?has_content> "
    template += "                <tr> "
    template += "                    <td align=\"left\" width=\"50%\"> "
    template += "                        <p align=\"left\"><b>Memo</b></p> "
    template += "                    </td> "
    template += "                    <td width=\"2%\"> "
    template += "                        <b>&nbsp;&nbsp;:&nbsp;&nbsp;</b> "
    template += "                    </td> "
    template += "                    <td align=\"left\" width=\"48%\"> "
    template += "                        <p class=\"alignL\">${record.memo}</p> "
    template += "                    </td> "
    template += "                </tr> "
    template += "</#if> "
    template += " "
    template += "            </table> "
    template += "        </td> "
    template += "    </tr> "
    template += "</table> "
    template += " "
    template += " "
    template += "<#if record.item?has_content> "
    template += "<table class=\"itemtable\" style=\"width: 100%;margin-top:10px;\"> "
    template += "    <tr> "
    template += "        <td align=\"left\" class=\"\"><b>Items</b></td> "
    template += "    </tr> "
    template += "</table> "
    template += "<#assign SrNo=0> "
    template += "    <table class=\"footertbl2\" id=\"itemtable\" style=\"width: 100%;margin-top:10px;\" width=\"100%\">                                                <!-- start items --> "
    template += "    <#list record.item as item> "
    template += "        <#if item_index==0><#assign grosstotalsum = 0> "
    template += "        <#assign amounttotalsum = 0><#assign taxamttotalsum = 0><#assign grossamttotalsum = 0> "
    template += "        <thead> "
    template += "            <tr style=\"padding-bottom: 0px;\"> "
    template += "                <th align=\"center\" width=\"4%\" class=\"td_right_line\"> "
    template += "                    <p align=\"left\"><b>Sl#</b></p> "
    template += "                </th> "
    template += "                <th align=\"left\" class=\"td_right_line\" width=\"23%\"> "
    template += "                    <p class=\"alignL\">Item Description</p> "
    template += "                </th> "
    template += "                <th align=\"center\" class=\"td_right_line\" width=\"5%\"> "
    template += "                    <p>Qty</p> "
    template += "                </th> "
    template += "                <th align=\"left\" class=\"td_right_line\" width=\"10%\"> "
    template += "                    <p>Unit</p> "
    template += "                </th> "
    template += "                <th align=\"right\" class=\"td_right_line\" width=\"12%\"> "
    template += "                    <p class=\"alignR\">Unit Rate</p> "
    template += "                </th> "
    template += "                <th align=\"right\" class=\"td_right_line\" width=\"13%\"> "
    template += "                    <p class=\"alignR\">Amount</p> "
    template += "                </th> "
    template += "                 <th align=\"right\" class=\"td_right_line\" width=\"12%\"> "
    template += "                    <p class=\"alignR\">Tax code</p> "
    template += "                </th> "
    template += "                <th align=\"right\" class=\"td_right_line\" width=\"8%\"> "
    template += "                    <p class=\"alignR\">Tax Rate</p> "
    template += "                </th> "
    template += "                <th align=\"right\" class=\"td_right_line\" width=\"12%\"> "
    template += "                    <p class=\"alignR\">Tax Amount</p> "
    template += "                </th> "
    template += "                <th align=\"right\" width=\"13%\"> "
    template += "                    <p class=\"alignR\">Gross Amount</p> "
    template += "                </th> "
    template += "            </tr> "
    template += "        </thead> "
    template += "</#if> "
    template += "                                      "
    template += "        <tr> "
    template += "            <td align=\"center\" class=\"td_top_line td_right_line\"> "
    template += "                <p align=\"center\"><#assign SrNo=SrNo + 1/>${SrNo}</p></td> "
    template += "            <td align=\"left\" class=\"td_top_line td_right_line\"> "
    template += "                <p class=\"alignL\">${item.item}<br/>${item.description}</p> "
    template += "            </td> "
    template += "            <td align=\"center\" class=\"td_top_line td_right_line\"> "
    template += "                <p class=\"alignC\">${item.quantity}</p> "
    template += "            </td> "
    template += "            <td align=\"left\" class=\"td_top_line td_right_line\"> "
    template += "                <p class=\"alignL\">${item.units}</p> "
    template += "            </td> "
    template += "            <td align=\"right\" class=\"td_top_line td_right_line\"> "
    template += "                <p class=\"alignR\">${item.rate?string[\"##,#00.00\"]}</p> "
    template += "            </td> "
    template += "            <td align=\"right\" class=\"td_top_line td_right_line\"> "
    template += "                <p class=\"alignR\">${item.amount?string('##,#00.00')}</p> "
    template += "            </td> "
    template += "             <td align=\"right\" class=\"td_top_line td_right_line\"> "
    template += "                <p class=\"alignR\">${item.taxcode}</p> "
    template += "            </td> "
    template += "            <td align=\"right\" class=\"td_top_line td_right_line\"> "
    template += "                <p class=\"alignR\">${item.taxrate1}</p> "
    template += "            </td> "
    template += "            "
    template += "            <td align=\"right\" class=\"td_top_line td_right_line\"> "
    template += "            <#if item.tax1amt?has_content> "
    template += "                <p class=\"alignR\">${item.tax1amt?string('##,#00.00')}</p> "
    template += "            </#if> "
    template += "            </td> "
    template += "             "
    template += "            <td align=\"right\" class=\"td_top_line \"> "
    template += "             <#if item.grossamt?has_content> "
    template += "                <p class=\"alignR\"> "
    template += "    ${item.grossamt?string('##,#00.00')}</p> "
    template += "            </#if> "
    template += "    <#assign amounttotalsum=amounttotalsum + item.amount/> "
    template += "    <#assign taxamttotalsum=taxamttotalsum + item.tax1amt/> "
    template += "    <#assign grossamttotalsum=grossamttotalsum + item.grossamt/> "
    template += "            </td> "
    template += "        </tr> "
    template += "</#list> "
    template += "    <tr> "
    template += "        <td align=\"right\" colspan=\"5\" class=\"td_right_line  td_top_line\" style=\"font-weight: bold;\">TOTAL</td> "
    template += "        <td align=\"right\" class=\"td_top_line td_right_line \"> "
    template += "            <#if amounttotalsum?has_content> "
    template += "            <p class=\"alignR\"><b>${amounttotalsum?string('##,#00.00')}</b></p> "
    template += "            </#if> "
    template += "        </td> "
    template += "        <td align=\"right\" class=\"td_top_line td_right_line \"> "
    template += "        </td> "
    template += "         <td align=\"right\" class=\"td_top_line td_right_line \"> "
    template += "        </td> "
    template += "        <td align=\"right\" class=\"td_top_line td_right_line \"> "
    template += "            <p class=\"alignR\"> "
    template += "            <!-- <#if taxamttotalsum?has_content> --> "
    template += "            <b>${taxamttotalsum}</b> "
    template += "            <!-- </#if>  --> "
    template += "            </p> "
    template += "        </td> "
    template += "        <td align=\"right\" class=\"td_top_line \"> "
    template += "         <#if amounttotalsum?has_content> "
    template += "            <p class=\"alignR\"><b>${grossamttotalsum?string('##,#00.00')}</b></p> "
    template += "           </#if>  "
    template += "        </td> "
    template += "    </tr> "
    template += "    <tr> "
    template += "        <td class=\"td_top_line \" colspan=\"10\"> "
    template += "            <p class=\"alignL\"><b>Amount in Words&nbsp;:&nbsp;${record.currencysymbol}&nbsp;${record.custbody_total_amount_in_words}</b></p> "
    template += "        </td> "
    template += "    </tr> "
    template += "</table> "
    template += "</#if> "
    template += "<#if record.expense?has_content> "
    template += "    <#assign TotalAmount = 0/> "
    template += "    <!-- <#assign itemExpTaxTotal = 0/> --> "
    template += "    <#assign TotalGrossAmount = 0/> "
    template += "    <!-- <#assign ttga = 0/> --> "
    template += "     <#assign amounttax=0/> "
    template += "    <#assign totaltax=0/> "
    template += "<table class=\"itemtable\" style=\"width: 100%;margin-top:10px;\"> "
    template += "    <tr> "
    template += "        <td align=\"left\" class=\"\"><b>Expense</b></td> "
    template += "    </tr> "
    template += "</table> "
    template += "<table class=\"itemtable\" style=\"width: 100%;\"><!-- start items --> "
    template += "    <#list record.expense as expense> "
    template += "    <#if expense_index==0> "
    template += " "
    template += "    <thead> "
    template += "    <tr> "
    template += "        <th align=\"left\" style=\"width:5%\" class=\"td_left_line td_top_line td_bottom_line\">Sl#</th> "
    template += "        <th align=\"left\" style=\"width:25%\"  class=\"td_left_line td_top_line td_bottom_line\"><p align=\"left\">Memo</p></th> "
    template += "        <th align=\"right\"  style=\"width:15%\" class=\"td_top_line td_left_line td_bottom_line\"><p align=\"right\">Amount</p></th> "
    template += "        <th align=\"right\" style=\"width:15%\" class=\"td_top_line td_left_line td_bottom_line\">Tax Code</th> "
    template += "        <th align=\"right\" style=\"width:15%\" class=\"td_top_line td_left_line td_bottom_line\">Tax Rate</th> "
    template += "        <th align=\"right\" style=\"width:15%\" class=\"td_top_line td_left_line td_bottom_line\"><p align=\"right\">Tax Amount</p></th> "
    template += "        <th align=\"right\" style=\"width:15%\" class=\"td_right_line td_top_line td_bottom_line td_left_line\"><p align=\"right\">Gross Amount</p></th> "
    template += "    </tr> "
    template += "    </thead> "
    template += "</#if> "
    template += "    <tr> "
    template += "        <td align=\"center\"  class=\"td_left_line td_bottom_line\">${expense_index + 1}</td> "
    template += "        <td align=\"left\"   class=\"td_left_line td_bottom_line\">${expense.memo}</td> "
    template += "        <td align=\"right\"  class=\"td_left_line td_bottom_line\">${expense.amount?string('##,#00.00')}</td> "
    template += "        <td align=\"right\"  class=\"td_left_line td_bottom_line\">${expense.taxcode}</td> "
    template += "        <td align=\"right\"  class=\"td_left_line td_bottom_line\">${expense.taxrate1}</td> "
    template += "        <!-- <td align=\"right\"  class=\"td_left_line td_bottom_line\">00.00</td> --> "
    template += "         "
    template += "        <td align=\"right\"  class=\"td_left_line td_bottom_line\"> "
    template += "        <#if expense.tax1amt?has_content> "
    template += "            ${expense.tax1amt?string('##,##0.00')} "
    template += "             </#if> "
    template += "            </td> "
    template += "            "
    template += "        <td class=\"td_left_line td_right_line td_bottom_line \" align=\"right\"> "
    template += "        <#if expense.grossamt?has_content> "
    template += "        <p>${expense.grossamt?string('##,#00.00')}</p> "
    template += "        </#if> "
    template += "        </td> "
    template += "    </tr> "
    template += "    <#assign TotalAmount = TotalAmount + expense.amount/> "
    template += "    <#assign TotalGrossAmount = TotalGrossAmount + expense.grossamt /> "
    template += "    <#assign totaltax=totaltax+expense.tax1amt> "
    template += "    </#list> "
    template += "    <tr> "
    template += "        <td align=\"right\" colspan=\"2\" class=\"td_left_line td_bottom_line\"><b>Total</b></td> "
    template += "        <td align=\"right\" class=\" td_right_line td_left_line td_bottom_line \"> "
    template += "            <p ><b>${TotalAmount?string[\"##,##0.00\"]}</b></p> "
    template += "        </td> "
    template += "        <td align=\"right\" class=\" td_right_line td_bottom_line \"></td> "
    template += "        <td align=\"right\" class=\" td_right_line td_bottom_line\"></td> "
    template += "         <td align=\"right\" class=\" td_bottom_line\"> "
    template += "          <#if totaltax?has_content> "
    template += "         <b>${totaltax?number?string[\"##,##0.00\"]}</b> "
    template += "         </#if> "
    template += "         </td> "
    template += "         <!-- <#if TotalGrossAmount?has_content> --> "
    template += "        <td  align=\"right\"  class=\"td_left_line td_right_line td_bottom_line\"> "
    template += "        <#if TotalGrossAmount?has_content> "
    template += "        <b >${TotalGrossAmount?number?string[\"##,##0.00\"]}</b> "
    template += "         </#if> "
    template += "         </td> "
    template += "        <!-- </#if> --> "
    template += "    </tr> "
    template += "    </table> "
    template += "</#if> "
    template += " "
    template += "<!-- <#if record.expense?has_content> "
    template += "    <#assign TotalAmount = 0/> "
    template += "    <#assign itemExpTaxTotal = 0/> "
    template += "    <#assign TotalGrossAmount = 0/> "
    template += "<table class=\"itemtable\" style=\"width: 100%;margin-top:10px;\"> "
    template += "    <tr> "
    template += "        <td align=\"left\" class=\"\"><b>Expense</b></td> "
    template += "    </tr> "
    template += "</table> "
    template += "<table class=\"itemtable\" style=\"width: 100%;\"><!- start items -> "
    template += "    <#list record.expense as expense> "
    template += "    <#if expense_index==0> "
    template += " "
    template += "    <thead> "
    template += "    <tr> "
    template += "        <th align=\"left\" style=\"width:5%\" class=\"td_left_line td_top_line td_bottom_line\">Sl#</th> "
    template += "        <th align=\"left\" style=\"width:25%\"  class=\"td_left_line td_top_line td_bottom_line\"><p align=\"left\">Memo</p></th> "
    template += "        <th align=\"right\"  style=\"width:15%\" class=\"td_top_line td_left_line td_bottom_line\"><p align=\"right\">Amount</p></th> "
    template += "        <th align=\"right\" style=\"width:15%\" class=\"td_top_line td_left_line td_bottom_line\">Tax Code</th> "
    template += "        <th align=\"right\" style=\"width:15%\" class=\"td_top_line td_left_line td_bottom_line\">Tax Rate</th> "
    template += "        <th align=\"right\" style=\"width:15%\" class=\"td_top_line td_left_line td_bottom_line\"><p align=\"right\">Tax Amount</p></th> "
    template += "        <th align=\"right\" style=\"width:15%\" class=\"td_right_line td_top_line td_bottom_line td_left_line\"><p align=\"right\">Gross Amount</p></th> "
    template += "    </tr> "
    template += "    </thead> "
    template += "</#if> "
    template += " "
    template += "    <tr> "
    template += "        <td align=\"center\"  class=\"td_left_line td_bottom_line\">${expense_index + 1}</td> "
    template += "        <td align=\"left\"   class=\"td_left_line td_bottom_line\">${expense.memo}</td> "
    template += "        <td align=\"right\"  class=\"td_left_line td_bottom_line\">${expense.amount?string('##,#00.00')}</td> "
    template += "        <td align=\"right\"  class=\"td_left_line td_bottom_line\">${expense.taxcode}</td> "
    template += "        <td align=\"right\"  class=\"td_left_line td_bottom_line\">${expense.taxrate1}</td> "
    template += "        <!- <#if expense.tax1amt?has_content> -> "
    template += "        <td align=\"right\"  class=\"td_left_line td_bottom_line\">${expense.tax1amt?string('##,#00.00')}</td> "
    template += "        <!- </#if> -> "
    template += "        <#assign Totalgrosstax = expense.tax1amt + expense.amount/> "
    template += "        <!- <#if expense.grossamt?has_content> -> "
    template += "        <td align=\"right\"  class=\"td_left_line td_right_line td_bottom_line\">${expense.amount?string('##,#00.00')}</td> "
    template += "          <!-</#if> -> "
    template += "    </tr> "
    template += "    <#assign TotalAmount = TotalAmount + expense.amount/> "
    template += "    <#assign TotalGrossAmount = TotalGrossAmount + expense.grossamt /> "
    template += "    <#assign itemExpTaxTotal=itemExpTaxTotal+expense.tax1amt/> "
    template += "    </#list> "
    template += "    <tr> "
    template += "        <td align=\"right\" colspan=\"2\" class=\"td_left_line td_bottom_line\"><b>Total</b></td> "
    template += "        <td align=\"right\" class=\"td_top_line td_right_line td_left_line td_bottom_line \"> "
    template += "              <!- <#if TotalAmount?has_content> -> "
    template += "            <p class=\"alignR\"><b>${TotalAmount?string('##,#00.00')}</b></p> "
    template += "            <!- </#if> -> "
    template += "        </td> "
    template += "        <td align=\"right\" class=\"td_top_line td_right_line td_bottom_line \"></td> "
    template += "        <td align=\"right\" class=\"td_top_line td_right_line td_bottom_line\"></td> "
    template += "         <td align=\"right\" class=\"td_top_line td_right_line td_bottom_line\"> "
    template += "                <!- <#if itemExpTaxTotal?has_content> -> "
    template += "                <b>${itemExpTaxTotal}</b> "
    template += "                <!- </#if> -> "
    template += "                </td> "
    template += "        <td align=\"right\" colspan=\"1\" class=\"td_left_line td_right_line td_bottom_line\"> "
    template += "        <!- <#if TotalGrossAmount?has_content> -> "
    template += "        <b>${TotalGrossAmount}</b> "
    template += "         <!- </#if> -> "
    template += "        </td> "
    template += "    </tr> "
    template += "    </table> "
    template += "</#if> --> "
    template += " "
    template += " "
    template += "<!-- <table style=\"width:100%;margin-top:10px;\"> "
    template += "    <tr> "
    template += "        <td align=\"left\" style=\"width:21%;\"><b>Terms and Conditions </b></td> "
    template += "        <td align=\"left\" style=\"width:2%;\">:</td> "
    template += "        <td align=\"left\" style=\"width:73%;\">${record.custbody_terms_conditions}</td> "
    template += "    </tr> "
    template += "</table> --> "
    template += " "
    template += "   "
    template += " "
    template += "<table style=\"width:100%;\"> "
    template += "    <tr> "
    template += "        <td align=\"center\">&nbsp;</td> "
    template += "    </tr> "
    template += "    <tr style=\"width:100%;padding-top: 20px;\"> "
    template += "        <td align=\"left\" style=\"width:40%;\"> "
    template += "            <table> "
    template += "            <#if record.custbody_created_by?has_content> "
    template += "             <tr> "
    template += "                    <td align=\"center\">${record.custbody_created_by}</td> "
    template += "                </tr> "
    template += "                 "
    template += "                <#else> "
    template += "                <tr> "
    template += "                    <td>___________________</td> "
    template += "                </tr> "
    template += "               </#if> "
    template += "               <tr> "
    template += "                    <td align=\"center\"> "
    template += "                        <b>Created By</b> "
    template += "                    </td> "
    template += "                </tr> "
    template += "            </table> "
    template += "        </td> "
    template += "        <td align=\"right\"> "
    template += "            <table align=\"right\"> "
    template += "                <tr> "
    template += "                    <td>___________________</td> "
    template += "                </tr> "
    template += "                <tr> "
    template += "                    <td align=\"center\"> "
    template += "                        <b>Approved By</b> "
    template += "                    </td> "
    template += "                </tr> "
    template += "            </table> "
    template += "        </td> "
    template += "    </tr> "
    template += "</table> "
    template += " "
    template += "</body> "
    template += "</pdf>"

    renderer.setTemplate(template);
    renderer.addRecord('record', billRec);
    var xml = renderer.renderToString();
    var file = nlapiXMLToPDF(xml);
    response.setContentType('PDF', 'Bill' + billRec.getFieldValue("id") + '.pdf', 'inline');
    response.write(file.getValue());


}

function replaceCharector(charVal) {
    return charVal.replace(/&/g, "&amp;");
}

function numberWithCommas(x) {
    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}