function printGRNAction(request, response) {
    var renderer = nlapiCreateTemplateRenderer();
    var recID = request.getParameter("recordID");
    // nlapiLogExecution('Debug', 'Transaction', 'Type : ' + recID);
    var renderer = nlapiCreateTemplateRenderer();
    var res = nlapiLoadRecord("itemreceipt", recID);
    var line_item_count = res.getLineItemCount("item");
    var invDetails = res.getLineItemCount("item");
    nlapiLogExecution('Debug', 'invDetails', + invDetails);

    template = '';
    template += '<?xml version=\"1.0\"?><!DOCTYPE pdf PUBLIC \"-//big.faceless.org//report\" \"report-1.1.dtd\"> ';
    template += '<pdf> ';
    template += '<head> ';
    template += '<link name=\"NotoSans\" type=\"font\" subtype=\"truetype\" src=\"${nsfont.NotoSans_Regular}\" src-bold=\"${nsfont.NotoSans_Bold}\" src-italic=\"${nsfont.NotoSans_Italic}\" src-bolditalic=\"${nsfont.NotoSans_BoldItalic}\" bytes=\"2\" /> ';
    template += '<#';



    template += 'if .locale == \"zh_CN\"> ';
    template += '<link name=\"NotoSansCJKsc\" type=\"font\" subtype=\"opentype\" src=\"${nsfont.NotoSansCJKsc_Regular}\" src-bold=\"${nsfont.NotoSansCJKsc_Bold}\" bytes=\"2\" /> ';
    template += '<#elseif .locale == \"zh_TW\"> ';
    template += '<link name=\"NotoSansCJKtc\" type=\"font\" subtype=\"opentype\" src=\"${nsfont.NotoSansCJKtc_Regular}\" src-bold=\"${nsfont.NotoSansCJKtc_Bold}\" bytes=\"2\" /> ';
    template += '<#elseif .locale == \"ja_JP\"> ';
    template += '<link name=\"NotoSansCJKjp\" type=\"font\" subtype=\"opentype\" src=\"${nsfont.NotoSansCJKjp_Regular}\" src-bold=\"${nsfont.NotoSansCJKjp_Bold}\" bytes=\"2\" /> ';
    template += '<#elseif .locale == \"ko_KR\"> ';
    template += '<link name=\"NotoSansCJKkr\" type=\"font\" subtype=\"opentype\" src=\"${nsfont.NotoSansCJKkr_Regular}\" src-bold=\"${nsfont.NotoSansCJKkr_Bold}\" bytes=\"2\" /> ';
    template += '<#elseif .locale == \"th_TH\"> ';
    template += '<link name=\"NotoSansThai\" type=\"font\" subtype=\"opentype\" src=\"${nsfont.NotoSansThai_Regular}\" src-bold=\"${nsfont.NotoSansThai_Bold}\" bytes=\"2\" /> ';
    template += '</#if> ';
    template += '<macrolist> ';
    template += '<macro id=\"nlheader\"> ';
    template += ' <#if companyInformation.logoUrl?has_content> ';
    template += '<table class=\"header\" style=\"width: 100%;\"> ';
    template += '<tr> ';
    template += ' ';
    template += ' ';
    template += '<td align=\"left\" valign=\"top\" width=\"100%\"> ';
    template += ' ';
    template += '                                            <img src=\"${companyInformation.logoUrl}\" style=\"width:250px;height:60px;position:absolute;top:30px\" /> ';
    template += ' ';
    template += '                                        </td> ';
    template += '</tr> ';
    template += '</table> ';
    template += '</#if> ';
    template += '</macro> ';
    template += '<#if (record.status == \"Pending Approval\") > ';
    template += '                            <macro id=\"watermark\"> ';
    template += '<div rotate=\"-45\" style=\"margin-top:400px;margin-left:50px;margin-right:50px;z-index:999;\" font-size=\"20pt\" color=\"#C0C0C0\"> ';
    template += '<p>PENDING FOR APPROVAL</p> ';
    template += '</div> ';
    template += '</macro> ';
    template += '</#if> ';
    template += ' ';
    template += '                            <macro id=\"nlfooter\"> ';
    template += '                                <table style=\"width: 100%;\"> ';
    template += '                                    <tr> ';
    template += '                                        <td align=\"left\" style=\"width:60%;\"> ';
    template += '                                            <p class=\"alignL\" style=\"font-size:11px;font-style:italics;color:#A9A9A9\">*This is a system-generated document. No signature is required.</p> ';
    template += '                                        </td> ';
    template += ' ';
    template += '                                        <td style=\"margin-left:150px;\">&nbsp;';



    template += '( Page <pagenumber/> ';
    template += ' of <totalpages/> ';
    template += ' )&nbsp;';



    template += '</td> ';
    template += '                                </tr> ';
    template += ' ';
    template += ' ';
    template += ' ';
    template += '                            </table> ';
    template += '                        </macro> ';
    template += '                    </macrolist> ';
    template += '                    <style type=\"text/css\">span, table ';
    template += '{                        <#if .locale=="zh_CN">font-family: stsong, sans-serif; ';
    template += '                            <#elseif .locale=="zh_TW">font-family: msung, sans-serif; ';
    template += '                                <#elseif .locale=="ja_JP">font-family: heiseimin, sans-serif; ';
    template += '                                    <#elseif .locale=="ko_KR">font-family: hygothic, sans-serif; ';
    template += '                                        <#elseif .locale=="ru_RU">font-family: verdana; ';
    template += '                                            <#else>font-family: sans-serif; ';
    template += '                                            </#if>font-size: 9pt; ';
    template += '		table-layout: fixed; ';
    template += '		} ';
    template += '		th ';
    template += '{		font-weight: bold; ';
    template += '		font-size: 8.5pt; ';
    template += '		padding-top: 2px; ';
    template += '		vertical-align: middle; ';
    template += '		/*padding: 3px 6px 10px;*/ ';
    template += '		/*background-color: #e3e3e3; ';
    template += '		color: #333333;*/ ';
    template += '		} ';
    template += '		b ';
    template += '{		font-weight: bold; ';
    template += '		color: #333333; ';
    template += '		} ';
    template += '		table.header td ';
    template += '{		padding: 0; ';
    template += '		font-size: 10pt; ';
    template += '		} ';
    template += '		table.footer td ';
    template += '{		padding: 0; ';
    template += '		font-size: 8pt; ';
    template += '		} ';
    template += '		#itemtable th p ';
    template += '{		vertical-align: text-top !important; ';
    template += '		text-align: center !important; ';
    template += '		} ';
    template += '		#itemtable ';
    template += '{		font-size: 8.5pt !important; ';
    template += '		border: 0.5px solid #000000 ';
    template += '		} ';
    template += '		table.total ';
    template += '{		page-break-inside: avoid; ';
    template += '		} ';
    template += '		tr.totalrow ';
    template += '{		background-color: #e3e3e3; ';
    template += '		line-height: 200%; ';
    template += '		} ';
    template += '		td.totalboxtop ';
    template += '{		font-size: 12pt; ';
    template += '		background-color: #e3e3e3; ';
    template += '		} ';
    template += '		span.title ';
    template += '{		font-size: 28pt; ';
    template += '		} ';
    template += '		.smallTitle ';
    template += '{		font-size: 9pt; ';
    template += '		} ';
    template += '		span.number ';
    template += '{		font-size: 16pt; ';
    template += '		text-align:center; ';
    template += '		} ';
    template += '		span.itemname ';
    template += '{		font-weight: bold; ';
    template += '		line-height: 150%; ';
    template += '		} ';
    template += '		hr ';
    template += '{		width: 100%; ';
    template += '		color: #d3d3d3; ';
    template += '		background-color: #d3d3d3; ';
    template += '		height: 1px; ';
    template += '		} ';
    template += '		table.smalltext tr td ';
    template += '{		font-size: 8pt; ';
    template += '		} ';
    template += '		/*table.itemtable th{ ';
    template += 'border-bottom: 10px #ffc966; ';
    template += 'border-color: yellow; ';
    template += '}*/ ';
    template += '		p.alignR ';
    template += '{		text-align: right !important; ';
    template += '		} ';
    template += '		p.alignL ';
    template += '{		text-align: left !important; ';
    template += '		} ';
    template += '		p.alignC ';
    template += '{		text-align: center !important; ';
    template += '		} ';
    template += '		.td_right_line ';
    template += '{		/*border-right: 0.5px solid #f4f4f4;*/ ';
    template += '		border-right :0.5px solid #000000; ';
    template += '		} ';
    template += '		.td_bottom_line ';
    template += '{		border-bottom: 0.5px solid #000000; ';
    template += '		} ';
    template += '		.td_top_line ';
    template += '{		/*border-top :0.5px solid #f4f4f4;*/ ';
    template += '		border-top :0.5px solid #000000; ';
    template += '		} ';
    template += '		.title ';
    template += '{		font-weight: bold; ';
    template += '		align:center!important; ';
    template += '		font-size:16pt; ';
    template += '		} ';
    template += '		.footer-img ';
    template += '{		/*width: 100%; ';
    template += '		height: 20%;*/ ';
    template += '		top: 0px; ';
    template += '		right: 0px; ';
    template += '		left: 0px; ';
    template += '		bottom: 0px; ';
    template += '		} ';
    template += '		.footer ';
    template += '{		margin-left:-45px; margin-right:-60px; margin-bottom:-115px; ';
    template += '		} ';
    template += '		.td_left_line ';
    template += '{		/*border-right: 0.5px solid #f4f4f4;*/ ';
    template += '		border-left :0.5px solid #000000; ';
    template += '		} ';
    template += '		.maintbl ';
    template += '{		border:0.5px solid #000000; ';
    template += '		} ';
    template += '		.footertbl ';
    template += '{		border:0.5px solid #000000; ';
    template += '		border-top: 0px !important; ';
    template += '		} ';
    template += '		.footertbl2 ';
    template += '{		 ';
    template += '		/*border:0.5px solid #000000;*/ ';
    template += '		border-left: 0.5px solid #000000; ';
    template += '		border-right: 0.5px solid #000000; ';
    template += '		border-top: 0.25px !important; ';
    template += '		} ';
    template += '		.pad_left ';
    template += '{		padding-left: 5px!important; ';
    template += '		} ';
    template += '		th,td ';
    template += '{		padding:4px; ';
    template += '		} ';
    template += '		                                                                                                                                                                                                                            <!--  .td_top_line td ';
    template += '{		padding-left: 5px!important; ';
    template += '		} --> ';
    template += '		td img ';
    template += '{		max-width:100%; ';
    template += '		 ';
    template += '		} ';
    template += '                                        </style> ';
    template += '                                    </head> ';
    template += '                                    <body header=\"nlheader\" background-macro=\"watermark\" header-height=\"10%\" footer=\"nlfooter\" footer-height=\"4%\" padding=\"0.25in 0.5in 0.25in 0.5in\" size=\"A4\">';
    template += '    <table width="100%" style="margin-top:60px;">';
    template += '    <tr>';
    template += '    <td align="center" class="title"><u>GOODS RECEIPT NOTE</u></td>';
    template += '    </tr>';
    template += '    </table>';
    template += ' <table style="width: 100%;border:0.5px Solid black;">';
    template += '    <tr>';
    template += '        <td>';
    template += '            <table style="width:100%">';
    template += '                 <tr>';
    template += '                    <td style="width:35%"><b>Supplier</b></td>';
    template += '                    <td style="width:2%"><b>:</b></td>';
    template += '                    <td style="width:63%"><b>${record.entity}</b></td>';
    template += '                </tr>';
    template += '             <#if record.createdfrom.tranid?has_content>';
    template += '                 <tr>';
    template += '                    <td style="width:35%"><b>LPO Ref</b></td>';
    template += '                    <td style="width:2%"><b>:</b></td>';
    template += '                    <td style="width:63%"><b>${record.createdfrom.tranid}</b></td>';
    template += '                </tr>';
    template += '                 </#if>';
    template += '             <#if record.entity.vatregnumber?has_content>';
    template += '                 <tr>';
    template += '                    <td style="width:35%"><b>Supplier TRN</b></td>';
    template += '                    <td style="width:2%"><b>:</b></td>';
    template += '                    <td style="width:63%"><b>${record.entity.vatregnumber}</b></td>';
    template += '                </tr>';
    template += '                 </#if>';
    template += '            </table>';
    template += '        </td>';
    template += '        <td style="border-left:0.5px Solid Black;">';
    template += '             <table style="width:100%">';
    template += '             <#if record.tranid?has_content>';
    template += '                <tr>';
    template += '                    <td style="width:35%"><b>Ref No</b></td>';
    template += '                    <td style="width:2%"><b>:</b></td>';
    template += '                    <td style="width:63%">${record.tranid}</td>';
    template += '                </tr>';
    template += '                 </#if>';
    template += '                  <#if record.trandate?has_content>';
    template += '                <tr>';
    template += '                    <td style="width:35%"><b>Date</b></td>';
    template += '                    <td style="width:2%"><b>:</b></td>';
    template += '                    <td style="width:63%">${record.trandate?string("dd-MMM-YYYY")}</td>';
    template += '                </tr>';
    template += '                 </#if>';
    // template += '                <#if companyInformation.employerid?has_content> ';
    template += '                <tr>';
    template += '                    <td style="width:35%"><b>TRN</b></td>';
    template += '                    <td style="width:2%"><b>:</b></td>';
    template += '                    <td style="width:63%"></td>';
    template += '                </tr>';
    //template += '                </#if> ';
    template += '                   <#if record.memo?has_content> ';
    template += '                <tr>';
    template += '                    <td style="width:35%"><b>Memo</b></td>';
    template += '                    <td style="width:2%"><b>:</b></td>';
    template += '                    <td style="width:63%">${record.memo}</td>';
    template += '                </tr>';
    template += '                 </#if> ';
    template += '            </table>';
    template += '        </td>';
    template += '    </tr>';
    template += '    </table>';
    template += '  <#if record.item?has_content>';
    template += '  <table  class="itemtable" style="width: 100%; margin-top: 10px;border-top:0.5px Solid black;border-left:0.5px Solid black;border-right:0.5px Solid black;">';
    template += '      <#list record.item as item><#if item_index==0>';
    template += '          <thead>';
    template += '              <tr>';
    template += '                  <th align="center" width="5%" class=" td_bottom_line">SL#</th>';
    template += '                  <th align="left" width="40%" class="td_left_line td_bottom_line"><p align="left">Item Description</p></th>';
    template += '                  <th align="center" width="30%" class="td_left_line td_bottom_line">Qty</th>';
    template += '                  <th align="center" width="25%" class="td_left_line td_bottom_line">Ratet</th>';
    template += '              </tr>';
    template += '          </thead>';
    template += '              </#if>';
    template += '   <tr class="td_bottom_line">';
    template += '                     <td align="center" >${item_index + 1}</td>';
    template += '                      <td align="left" class="td_left_line ">${item.item}<br/>${item.description}</td>';
    template += '                      <td align="center" class="td_left_line ">${item.quantity}</td>';
    template += '                      <td align="center" class="td_left_line ">${item.rate?string("###00.00;(###00.00)")}</td>';
    template += '     </tr> ';
    template += '      </#list> ';

    template += '      </table>';
    template += '  </#if>';

    template += '<table style="width:100%;">';
    template += ' <tr>';
    template += '                        <td align="center">&nbsp;</td>';
    template += '                    </tr>';
    template += '                                                                        <tr style="width:100%;padding-top: 20px;">';
    template += '                                                                            <td align="left" style="width:40%;">';
    template += '                                                                                <table>';
    template += '                                                                                    <tr>';
    template += '                                                                                        <td align="center">';
    template += '                                                                                            <b>Received By</b>';
    template += '                                                                                        </td>';
    template += '                                                                                    </tr>';
    template += '                                                                                    <tr>';
    template += '                                                                                        <td>';
    template += '                                                                                            <b>Signature</b>';
    template += '                                                                                        </td>';
    template += '                                                                                        <td><b>:</b></td>'
    template += '                                                                                    </tr>';
    template += '                                                                                    <tr>';
    template += '                                                                                        <td></td>';
    template += '                                                                                        <td></td>'
    template += '                                                                                    </tr>';
    template += '                                                                                </table>';
    template += '                                                                            </td>';
    template += '                                                                            <td align="right">';
    template += '                                                                                <table align="right">';
    template += '                                                                                    <tr>';
    template += '                                                                                        <td>___________________</td>';
    template += '                                                                                    </tr>';
    template += '                                                                                    <tr>';
    template += '                                                                                        <td align="center">${record.custbody_created_by}</td>';
    template += '                                                                                    </tr>';
    template += '                                                                                    <tr>';
    template += '                                                                                        <td align="center">';
    template += '                                                                                             <b>Created By</b>';
    template += '                                                                                         </td>';
    template += '                                                                                     </tr>';
    template += '                                                                                 </table>';
    template += '                                                                             </td>';
    template += '                                                                         </tr>';
    template += '                                                                     </table>';



    template += '</body>';
    template += '           </pdf>';
    renderer.setTemplate(template);
    renderer.addRecord('record', res);
    var xml = renderer.renderToString();
    var file = nlapiXMLToPDF(xml);
    response.setContentType('PDF', 'GRN_' + res.getFieldValue("id") + '.pdf', 'inline');
    response.write(file.getValue());
}

