function printNewLH(request, response) {';
template+='	var invID = request.getParameter("recid");';
template+='	var purchRec = nlapiLoadRecord('purchaseorder', invID);';
template+='	var renderer = nlapiCreateTemplateRenderer();';
template+='	var template = '';';
template+='<? xml version = "1.0" ?>< !DOCTYPE pdf PUBLIC "-//big.faceless.org//report" "report-1.1.dtd" >';
template+='<pdf>';
template+='<head>';
template+='	<link name="NotoSans" type="font" subtype="truetype" src="${nsfont.NotoSans_Regular}" src-bold="${nsfont.NotoSans_Bold}" src-italic="${nsfont.NotoSans_Italic}" src-bolditalic="${nsfont.NotoSans_BoldItalic}" bytes="2" />';
template+='	<#if .locale == "zh_CN">';
template+='		<link name="NotoSansCJKsc" type="font" subtype="opentype" src="${nsfont.NotoSansCJKsc_Regular}" src-bold="${nsfont.NotoSansCJKsc_Bold}" bytes="2" />';
template+='	<#elseif .locale == "zh_TW">';
template+='		<link name="NotoSansCJKtc" type="font" subtype="opentype" src="${nsfont.NotoSansCJKtc_Regular}" src-bold="${nsfont.NotoSansCJKtc_Bold}" bytes="2" />';
template+='	<#elseif .locale == "ja_JP">';
template+='		<link name="NotoSansCJKjp" type="font" subtype="opentype" src="${nsfont.NotoSansCJKjp_Regular}" src-bold="${nsfont.NotoSansCJKjp_Bold}" bytes="2" />';
template+='	<#elseif .locale == "ko_KR">';
template+='		<link name="NotoSansCJKkr" type="font" subtype="opentype" src="${nsfont.NotoSansCJKkr_Regular}" src-bold="${nsfont.NotoSansCJKkr_Bold}" bytes="2" />';
template+='	<#elseif .locale == "th_TH">';
template+='		<link name="NotoSansThai" type="font" subtype="opentype" src="${nsfont.NotoSansThai_Regular}" src-bold="${nsfont.NotoSansThai_Bold}" bytes="2" />';
template+='	</#if>';
template+='    <macrolist>';
template+='        <macro id="nlheader">';
template+='            <table style="width: 100%; font-size: 8pt;"><tr>';
template+='              <td rowspan="3" style="padding: 0;width:40%;"><#if companyInformation.logoUrl?length != 0><img src="${companyInformation.logoUrl}" style="float: left; margin: 7px;width:150px;height:100px;"/></#if></td>';
template+='              <td align="right" style="width:20%;" >#${record.tranid}<br/> ${companyInformation.companyName}<br />${companyInformation.addressText}<br/> ${record.trandate}</td>';
template+='             <!-- <td align="right" style="padding: 0;width:15%;"><span >${record@title}</span></td>';
template+='        <td align="right" style="padding: 0;width:15%;"><span>#${record.tranid}</span></td>';
template+='              <td align="right" style="padding: 0;width:15%;">${record.trandate}</td>-->';
template+='	</tr>';
template+='	</table>';
template+='        </macro>';
template+='        <macro id="nlfooter">';
template+='            <table style="width: 100%; font-size: 8pt;"><tr>';
template+='	<td style="padding: 0;"><barcode codetype="code128" showtext="true" value="${record.tranid}"/></td>';
template+='	<td align="right" style="padding: 0;"><pagenumber/> of <totalpages/></td>';
template+='	</tr></table>';
template+='        </macro>';
template+='    </macrolist>';
template+='    <style type="text/css">* {';
template+='		<#if .locale == "zh_CN">';
template+='			font-family: NotoSans, NotoSansCJKsc, sans-serif;';
template+='		<#elseif .locale == "zh_TW">';
template+='			font-family: NotoSans, NotoSansCJKtc, sans-serif;';
template+='		<#elseif .locale == "ja_JP">';
template+='			font-family: NotoSans, NotoSansCJKjp, sans-serif;';
template+='		<#elseif .locale == "ko_KR">';
template+='			font-family: NotoSans, NotoSansCJKkr, sans-serif;';
template+='		<#elseif .locale == "th_TH">';
template+='			font-family: NotoSans, NotoSansThai, sans-serif;';
template+='		<#else>';
template+='			font-family: NotoSans, sans-serif;';
template+='		</#if>';
template+='		}';
template+='		table {';
template+='			font-size: 9px;';
template+='			table-layout: fixed;';
template+='		}';
template+='        th {';
template+='            font-weight: bold;';
template+='            font-size: 8pt;';
template+='            vertical-align: middle;';
template+='            padding: 7px;';
template+='            background-color: #e3e3e3;';
template+='            color: #333333;';
template+='        }';
template+='        td {';
template+='            padding:7px;';
template+='        }';
template+='		td p { align:left }';
template+='</style>';
template+='';
template+='</head >';
template+='<body  style="margin-top:20px;" header="nlheader" header-height="10%" footer="nlfooter" footer-height="20pt" padding="0.5in 0.5in 0.5in 0.5in" size="Letter">';
template+='';
template+='<h4 style="width:100%;  text-align: center;padding-top:40px;"> <strong><u>SALES ORDER</u></strong></h4>';
template+='<table  style="border: 1px solid black;">';
template+='        <tr  style="border-bottom: 1px solid black;">';
template+='            <th style="text-align:center" colspan="6">Customer Information </th>';
template+='            <th colspan="7"> Sales Rep</th>';
template+='        </tr>';
template+='        <tr >';
template+='            <td  colspan="3"> Name:</td>';
template+='			<td style="border-right:1px solid black;" colspan="3">${record.entity}</td>';
template+='           <td colspan="3">Sales Rep:</td>';
template+='		   <td colspan="4">${record.salesrep}</td>';
template+='        </tr>';
template+='        <tr  >';
template+='            <td  colspan="3">Contact:</td>';
template+='			<td style="border-right: 1px solid black;" colspan="3">${record.entity.isperson}</td>';
template+='            <td colspan="3">Email:</td>';
template+='			<td colspan="4">${record.email}</td>';
template+='        </tr>';
template+='        <tr >';
template+='            <td  colspan="3">Address:</td>';
template+='		<td style="border-right:1px solid black;" colspan="3"></td>';
template+='            <td colspan="3">Mobile:</td>';
template+='         <td colspan="4">${record.entity.isperson}</td>';
template+='        </tr>';
template+='';
template+='        <tr>';
template+='            <td   colspan="3">City, ST, Zip:</td>';
template+='			<td style="border-right:1px solid black;" colspan="3">${record.location}</td>';
template+='          <td Colspan="3"> Date:</td>';
template+='          <td colspan="3">${record.trandate?string("yyyy/MM/dd")}</td>';
template+='        </tr>';
template+='        <tr>';
template+='            <td  colspan="3">Phone:</td>';
template+='				<td style="border-right:1px solid black;"  colspan="3">${record.location}</td>';
template+='          <td>${"abcdef"?remove_ending("def")}</td>';
template+='        </tr>';
template+='';
template+='        <tr>';
template+='            <td  colspan="3">Fax:</td>';
template+='			<td style="border-right:1px solid black;" colspan="3">${record.entity.fax}</td>';
template+='        </tr>';
template+='        <tr>';
template+='            <td    colspan="3">Email:</td>';
template+='			<td style="border-right:1px solid black;" colspan="3">${record.email}</td>';
template+='        </tr>';
template+='';
template+='        <tr style="border-bottom: 1px solid black;" >';
template+='            <td  colspan="3">VAT #:</td>';
template+='			<td style="border-right:1px solid black;" colspan="3"></td>';
template+='        </tr>';
template+='        <tr >';
template+='            <th  style="border-bottom: 1px solid black;">SL# </th>';
template+='            <th  style="border-bottom: 1px solid black;">Item</th>';
template+='            <th  style="border-bottom: 1px solid black;">Description</th>';
template+='            <th  style="border-bottom: 1px solid black;" colspan="2">Rental Type</th>';
template+='            <th  style="border-bottom: 1px solid black;">No.of H/D/W/M</th>';
template+='            <th  style="border-bottom: 1px solid black;">Qty</th>';
template+='            <th  style="border-bottom: 1px solid black;">Rate </th>';
template+='            <th  style="border-bottom: 1px solid black;"> Amount</th>';
template+='            <th  style="border-bottom: 1px solid black;">Tax%</th>';
template+='            <th  style="border-bottom: 1px solid black;"> Tax Amt</th>';
template+='            <th  style="border-bottom: 1px solid black;"  colspan="2">Gross Amt</th>';
template+='        </tr>';
template+='		<#assign SL=0>';
template+='          <#assign subtotal=0.00>';
template+='	<#if record.item?has_content>';
template+='	<#list record.item as item>';
template+='		<#assign SL=SL+1/>';
template+='		<tr  style="border-bottom:1px solid black;" >';
template+='		<td>${SL?is_nan}</td>';
template+='		<td>${item.item}</td>';
template+='		<td>${item.description}</td>';
template+='		<td colspan="2">${item.custcol_rent_from_date}</td>';
template+='		<td>${item.custcol_rent_no_of_hdwm}</td>';
template+='		<td>${item.quantity}</td>';
template+='		<td>${item.rate}</td>';
template+='		<td>${item.amount}</td>';
template+='		<td>${item.taxcodeem}</td>';
template+='		<td>${item.taxcode_display}</td>';
template+='		<td  colspan="2">${item.amount?string.currency}</td>';
template+='		</tr>';
template+='      <#assign subtotal=subtotal+item.amount>';
template+='		</#list>';
template+='		</#if>';
template+='        <tr>';
template+='            <td  style="border-right:1px solid black;" rowspan="4" colspan="6">${"comments:"?cap_first} (Optional if any) </td>';
template+='		</tr>';
template+='      <#assign total=subtotal>';
template+='		<tr >';
template+='		<td  colspan="3">Sub Total</td>';
template+='          <td colspan="4">${subtotal?string["#,##0.00"]}</td>';
template+='		</tr>';
template+='		<tr >';
template+='		<td  colspan="3" style="border-bottom:1px solid black;">${"total VAT Amount"?cap_first}</td>';
template+='          <td colspan="4" style="border-bottom:1px solid black;">${00?string.percent}</td>';
template+='		</tr>';
template+='		<tr>';
template+='		<td colspan="3">Total (Including Taxes)</td>';
template+='          <td colspan="4">${subtotal?string["#,##0.00"]}</td>';
template+='		</tr>';
template+='    </table>';
template+='';
template+='<p style="font-size:10px;">Note:Total Amount Excluding VAT';
template+='  </p>';
template+='';
template+='    <table style="width:100%;margin-top:50px;">';
template+='        <tr>';
template+='            <td style="width:43%;text-align: center;">_________________</td>';
template+='            <td style="width:43%;text-align: center">___________________</td>';
template+='            <td style="width:14%;text-align: center">____________________</td>';
template+='        </tr>';
template+='      <tr>';
template+='      <td style="width:43%;text-align: center;margin-left:10px;">Created By</td>';
template+='      <td  style="width:43%;text-align: center;margin-left:10px;">Approved By</td>';
template+='      <td  style="width:14%;text-align: center;margin-left:6px;">Acknowledge By</td></tr>';
template+='    </table>';
template+='      <#assign testlist=[';
template+='		0, 1, -1, 0.5, 1.5, -0.5,';
template+='		-1.5, 0.25, -0.25, 1.75, -1.75] >';
template+='<#list testlist as result>';
template+='    ${result} floor=${result?floor} &nbsp;&nbsp;ceiling=${result?ceiling} &nbsp;&nbsp;round=${result?round}<br/>';
template+='</#list>';
template+='<!--< table >';
template+='';
template+='</table >';
template+='    <table style="width: 100%; margin-top: 10px;"><tr>-->';
template+='	<!--<td colspan="3" style="font-size: 8pt; padding: 6px 0 2px; font-weight: bold; color: #333333;">${record.billaddress@label}</td>';
template+='	<td colspan="3" style="font-size: 8pt; padding: 6px 0 2px; font-weight: bold; color: #333333;">${record.shipaddress@label}</td>';
template+='	<td colspan="5" style="font-size: 12pt; background-color: #e3e3e3; font-weight: bold;">${record.total@label?upper_case}</td>';
template+='	</tr>';
template+='	<tr>';
template+='	<td colspan="3" style="padding: 0;">${record.billaddress}</td>';
template+='	<td colspan="3" style="padding: 0;">${record.shipaddress}</td>';
template+='	<td align="right" colspan="5" style="font-size: 28pt; padding-top: 20px; background-color: #e3e3e3;">${record.total}</td>';
template+='	</tr></table>';
template+='';
template+='	<th>${record.paymentmethod@label}</th>';
template+='	<th>${record.otherrefnum@label}</th>';
template+='	<th>${record.shipmethod@label}</th>';
template+='	<th>${record.shipdate@label}</th>';
template+='	</tr >';
template+='		<tr>';
template+='			<td style="padding-top: 2px;">${record.paymentmethod}</td>';
template+='			<td style="padding-top: 2px;">${record.otherrefnum}</td>';
template+='			<td style="padding-top: 2px;">${record.shipmethod}</td>';
template+='			<td style="padding-top: 2px;">${record.shipdate}</td>';
template+='		</tr></table >';
template+='			<#if record.item?has_content>-->';
template+='';
template+='				<!--<table style="width: 100%; margin-top: 10px;"><start items ><#list record.item as item><#if item_index==0>';
template+='					<thead>';
template+='						<tr>';
template+='							<th align="center" colspan="3" style="padding: 10px 6px;">${item.quantity@label}</th>';
template+='							<th colspan="12" style="padding: 10px 6px;">${item.item@label}</th>';
template+='							<th align="right" colspan="4" style="padding: 10px 6px;">${item.rate@label}</th>';
template+='							<th align="right" colspan="4" style="padding: 10px 6px;">${item.amount@label}</th>';
template+='						</tr>';
template+='					</thead>';
template+='				</#if><tr>';
template+='						<td align="center" colspan="3" line-height="150%">${item.quantity}</td>';
template+='						<td colspan="12"><span style="font-weight: bold; line-height: 150%; color: #333333;">${item.item}</span><br />${item.description}</td>';
template+='						<td align="right" colspan="4">${item.rate}</td>';
template+='						<td align="right" colspan="4">${item.amount}</td>';
template+='					</tr>';
template+='				</#list>< end items></table>';
template+='';
template+='				<hr style="width: 100%; color: #d3d3d3; background-color: #d3d3d3; height: 1px;" /></#if>-->';
template+='< !--< table style = "page-break-inside: avoid; width: 100%; margin-top: 10px;" ><tr>';
template+='	<td colspan="4">&nbsp;</td>';
template+='	<td align="right" style="font-weight: bold; color: #333333;">${record.subtotal@label}</td>';
template+='	<td align="right">${record.subtotal}</td>';
template+='	</tr>';
template+='	<tr>';
template+='	<td colspan="4">&nbsp;</td>';
template+='	<td align="right" style="font-weight: bold; color: #333333;">${record.taxtotal@label} (${record.taxrate}%)</td>';
template+='	<td align="right">${record.taxtotal}</td>';
template+='	</tr>';
template+='	<tr style="background-color: #e3e3e3; line-height: 200%;">';
template+='	<td background-color="#ffffff" colspan="4">&nbsp;</td>';
template+='	<td align="right" style="font-weight: bold; color: #333333;">${record.total@label}</td>';
template+='	<td align="right">${record.total}</td>';
template+='	</tr></table > -->';
template+='</body >';
template+='</pdf ';>template+='